spring:
  application:
    name: equipofutbol-adso
  datasource:
    url: jdbc:mysql://${BD_HOST:localhost}:${BD_PORT:3306}/${BD_NAME:futbol}
    username: ${BD_USER:root}
    password: ${BD_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:9090}
  servlet:
    context-path: /api/v1/

security:
  jwt:
    secret-key: WCrD7ZwsNH2yZx4d29X3522BEAYTjm7BiNJxi9xksjU=
    token-expiration: 600000
